spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/mules_data
        username: mules_data_api
        password: p397wDwKGhlfyGqseWzb
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                ddl-auto: create-drop